import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { study, dates, type Input, type Member } from '../src/package-study.ts';
const members: Member[] = JSON.parse(readFileSync('config/package-study-members.json', 'utf8'));
const input = (): Input => ({ asOf: '2026-12-03T01:00:00Z', members, series: Object.fromEntries(members.map(m => [m.id,
  dates(['2026-09-10', '2026-12-02']).map(d => ({ d, n: 5, vwap: m.group === 'treatment' && d >= '2026-10-22' ? 120 : 100 }))])) });
const r = study(input());
assert.equal(r.results.h2.status, 'ready');
assert(Math.abs(r.results.h2.relativePercent! - 20) < 1e-9, '로그 효과를 정확히 상대 %로 변환');
assert.equal(r.results.h2.pre.valid, 42);
assert.equal(r.results.h2.post.valid, 14);
assert.equal(r.preExpiryMargin.status, 'ready');
assert(Math.abs(r.preExpiryMargin.meanPercent! - 385) < 1e-9);
for (const h of ['h1', 'h3', 'h4', 'h5'] as const) {
  assert.equal(r.results[h].status, 'not_applicable');
  assert.equal(r.results[h].relativePercent, null, '삭제 후 행이 있어도 효과를 계산하지 않음');
}
assert.equal(r.audit.filter(m => m.postExpiryRows.length > 0).length, 7);
assert.equal(r.timePlacebo.values.length, 29);
assert.equal(r.timePlacebo.usableThursdays, 5);
const before = input(); before.asOf = '2026-11-04T14:59:59Z';
assert.equal(study(before).results.h2.status, 'pending', 'KST 당일 미완성 봉 제외');
before.asOf = '2026-11-04T15:00:00Z';
assert.equal(study(before).results.h2.status, 'ready', 'KST 11-05에 11-04 일봉 완료');
const gap = input();
gap.series[members[0].id] = gap.series[members[0].id].filter(r => !['2026-10-22', '2026-10-23'].includes(r.d));
assert.equal(study(gap).results.h2.post.valid, 12);
assert(Math.abs(study(gap).results.h2.relativePercent! - 20) < 1e-9);
gap.series[members[0].id] = gap.series[members[0].id].filter(r => r.d !== '2026-10-24');
assert.equal(study(gap).results.h2.status, 'insufficient', '구성원 하나의 결측도 집단 날짜를 제외');
assert.equal(study(gap).results.h2.relativePercent, null);
const thin = input(); thin.series[members[0].id].forEach(r => { if (r.d >= '2026-10-22') r.n = 4; });
assert.equal(study(thin).results.h2.status, 'insufficient');
assert.equal(study(thin, 3).results.h2.status, 'ready');
const baseGap = input(); baseGap.series[members[0].id] = baseGap.series[members[0].id].filter(r => r.d > '2026-09-18');
assert.equal(study(baseGap).results.h2.pre.valid, 33);
assert.equal(study(baseGap).results.h2.status, 'insufficient');
const bad = input(); bad.series[members[0].id].push(bad.series[members[0].id][0]);
assert.throws(() => study(bad), /잘못된 일봉/);
assert.throws(() => study({ ...input(), asOf: 'unknown' }), /기준 시각/);
assert.throws(() => study({ ...input(), members: members.slice(1) }), /21종/);
const future = input(); future.asOf = '2026-09-28T00:00:00Z';
assert.equal(study(future).sensitivity.h2, null, '추정 구간이 끝나기 전 민감도 확정 금지');
assert.equal(study(future).diagnostics.treatment.dailyChangeCorrelation, null, '상수 시계열 상관은 정의되지 않음');
const varying = input();
varying.series[members[0].id].forEach((r, i) => { r.vwap *= Math.exp(Math.sin(i) / 100); });
assert(study(varying).sensitivity.h2!.relativePercent > 0);
const snapshot: Input = JSON.parse(readFileSync('docs/evidence/package-study-input-20260928.json', 'utf8'));
assert.deepEqual(study(snapshot).groupCoverage, { treatment: 18, control: 18, spillover: 7 }, '공개한 초기 감사 입력 재현');
assert.equal(study(snapshot).audit.find(m => m.name === '종이달 오르골 칭호 선택 상자')!.valid, 8);
console.log('package-study: 기간 경계·20% 효과·고정 구성·결측·거래 기준·삭제·플라시보·민감도 통과');
