import assert from 'node:assert/strict';
import {studySeries,features,classify,score,paired} from '../src/intraday-joint-forecast.ts';
import {H,D,type Series} from '../src/activity-study.ts';
const start=Date.parse('2026-09-01T00:00:00Z');
const s:Series={id:'test',name:'test',category:'test',points:Array.from({length:24*24},(_,i)=>({t:start+i*H,price:100*Math.exp(-i*.0001+.01*Math.sin(i*Math.PI/12)),stock:100+i%12,known:true,clean:true}))};
const cutoff=start+24*D,result=studySeries(s,cutoff),row=result.rows.find(r=>r.actual!=null)!;
assert(result.coverage.scored>8);
const futureChanged={...s,points:s.points.map(p=>p.t>row.origin?{...p,price:p.price*2,stock:9000}:p)};
assert.deepEqual(studySeries(futureChanged,cutoff).rows.find(r=>r.origin===row.origin)!.predictions,row.predictions,'future target/stock cannot alter forecast');
const targetMissing={...s,points:s.points.filter(p=>p.t!==row.origin+11*H)};
const missingRow=studySeries(targetMissing,cutoff).rows.find(r=>r.origin===row.origin)!;
assert.equal(missingRow.actual,null);assert.deepEqual(missingRow.predictions,row.predictions,'missing future target must not suppress prediction');
const map=new Map(s.points.map(p=>[p.t,p]));map.delete(row.origin-24*H);
assert.equal(features(map,row.origin,10),null,'no interpolation of exact lag');
const c=classify([-2,0,2],[-2,0,2],.5);assert.equal(c.accuracy,1);assert.equal(c.balancedAccuracy,1);
assert.deepEqual(classify([-.5,.5],[0,0],.5).support,[0,2,0]);
assert.equal(score([missingRow]).days,0);
assert.equal(paired(result.rows,'hold','hold').meanDifference,0);
assert.deepEqual(paired(result.rows,'stock','clock'),paired(result.rows,'stock','clock'),'fixed bootstrap seed');
console.log('joint forecast: future-price/stock leakage, target coverage, exact lags, labels and paired blocks passed');
